START TRANSACTION;

-- =========================
-- ARTICULOS DE PINTURERIA (46 registros)
-- =========================
INSERT INTO articulo (cod_articulo, nombre, descripcion, unidad_medida) VALUES
(24023, 'Rodillo de lana completo pelo natural (no sintético) Nº 18', 'Rodillo de lana completo pelo natural (no sintético) Nº 18', 'Unidad'),
(24024, 'Lija circular con velcro para maquina lijadora roto orbital (125 mm) Nº 80', 'Lija circular con velcro para maquina lijadora roto orbital (125 mm) Nº 80', 'Unidad'),
(24025, 'Lija circular con velcro para maquina lijadora roto orbital (125 mm) Nº 100', 'Lija circular con velcro para maquina lijadora roto orbital (125 mm) Nº 100', 'Unidad'),
(24026, 'Lija circular con velcro para maquina lijadora roto orbital (125 mm) Nº 150', 'Lija circular con velcro para maquina lijadora roto orbital (125 mm) Nº 150', 'Unidad'),
(24027, 'Pintura latex acrilico antihongo negro', 'Pintura latex acrilico antihongo negro', 'Litro'),
(24001, 'Pintura latex antihongo interior-exterior mate base blanca', 'Pintura latex antihongo interior-exterior mate base blanca', 'Litro'),
(24002, 'Pintura latex interior mate base blanca', 'Pintura latex interior mate base blanca', 'Litro'),
(24003, 'Thinner Diluyente', 'Thinner Diluyente', 'Litro'),
(24004, 'Diluyente aguarrás', 'Diluyente aguarrás', 'Litro'),
(24005, 'Esmalte satinado al agua negro', 'Esmalte satinado al agua negro', 'Litro'),
(24006, 'Esmalte satinado al agua blanco', 'Esmalte satinado al agua blanco', 'Litro'),
(24007, 'Viruta grosor mediano', 'Viruta grosor mediano', 'Paquete'),
(24008, 'Viruta grosor fino', 'Viruta grosor fino', 'Paquete'),
(24009, 'Esmalte satinado al aceite blanco', 'Esmalte satinado al aceite blanco', 'Litro'),
(24010, 'Impermeabilizante acrilico elástico p/ frentes y muros transparente', 'Impermeabilizante acrilico elástico p/ frentes y muros transparente', 'Litro'),
(24011, 'Esmalte sintético 3 en 1 negro', 'Esmalte sintético 3 en 1 negro', 'Litro'),
(24012, 'Esmalte sintético 3 en 1 blanco', 'Esmalte sintético 3 en 1 blanco', 'Litro'),
(24013, 'Cinta papel de pintor para enmascarar de 36mm x 50m', 'Cinta papel de pintor para enmascarar de 36mm x 50m', 'Rollo'),
(24014, 'Cinta papel de pintor para enmascarar de 24mm x 50m', 'Cinta papel de pintor para enmascarar de 24mm x 50m', 'Rollo'),
(24015, 'Cinta papel de pintor para enmascarar de 48mm x 50m', 'Cinta papel de pintor para enmascarar de 48mm x 50m', 'Rollo'),
(24016, 'Mezcla adhesiva a base de yeso para interior', 'Mezcla adhesiva a base de yeso para interior', 'Unidad'),
(24017, 'Mezcla adhesiva a base de yeso para exterior', 'Mezcla adhesiva a base de yeso para exterior', 'Unidad'),
(24018, 'Pincel Nº 30 cerda blanca', 'Pincel Nº 30 cerda blanca', 'Unidad'),
(24019, 'Pincel Nº 25 cerda blanca', 'Pincel Nº 25 cerda blanca', 'Unidad'),
(24020, 'Pincel Nº 10 cerda blanca', 'Pincel Nº 10 cerda blanca', 'Unidad'),
(24021, 'Bandeja plástica de pintor para colgar', 'Bandeja plástica de pintor para colgar', 'Unidad'),
(24022, 'Rodillo de lana completo pelo natural (no sintético) Nº 22', 'Rodillo de lana completo pelo natural (no sintético) Nº 22', 'Unidad'),
(24288, 'Impermeabilizante Fibrado p/techos', 'Impermeabilizante Fibrado p/techos', 'Unidad'),
(24289, 'Impermeabilizante con poliuretano rojo p/techos', 'Impermeabilizante con poliuretano rojo p/techos', 'Litro'),
(24528, 'Espátula para pintor', 'Espátula para pintor', 'Litro'),
(24529, 'Rodillo para pintar epoxi Nº 5', 'Rodillo para pintar epoxi Nº 5', 'Unidad'),
(24530, 'Rodillo para pintar epoxi Nº 10', 'Rodillo para pintar epoxi Nº 10', 'Unidad'),
(24531, 'Extensor telescópico para pintor', 'Extensor telescópico para pintor', 'Unidad'),
(24532, 'Pintura para piso', 'Pintura para piso', 'Litro'),
(24503, 'Lija', 'Lija', 'Unidad'),
(24505, 'Removedor de Pinturas', 'Removedor de Pinturas', 'Litro'),
(24751, 'Pistola para pintar', 'Pistola para pintar', 'Unidad'),
(25130, 'Entonador de pinturas color negro', 'Entonador de pinturas color negro', 'Sachet'),
(25134, 'Entonador de pinturas color marrón', 'Entonador de pinturas color marrón', 'Sachet'),
(25135, 'Entonador de pinturas color ocre', 'Entonador de pinturas color ocre', 'Sachet'),
(25317, 'Lija Nº 80', 'Lija Nº 80', 'Unidad'),
(25318, 'Lija Nº 100', 'Lija Nº 100', 'Unidad'),
(25319, 'Lija Nº 150', 'Lija Nº 150', 'Unidad'),
(25320, 'Lija Nº 240', 'Lija Nº 240', 'Unidad'),
(5006, 'Máquina para pintar', 'Máquina para pintar', 'Unidad');

COMMIT;